// <auto-generated />
using System;
using BankAccountManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankAccountManagement.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20260522063459_AdjustDatePrecision")]
    partial class AdjustDatePrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BankAccountManagement.Models.Account", b =>
                {
                    b.Property<long>("AccountId")
                        .HasColumnType("bigint")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("account_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.HasKey("AccountId");

                    b.HasIndex("CustomerId");

                    b.ToTable("accounts", (string)null);

                    b.HasDiscriminator<string>("account_type").HasValue("Account");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BankAccountManagement.Models.Customer", b =>
                {
                    b.Property<long>("CustomerId")
                        .HasColumnType("bigint")
                        .HasColumnName("customer_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("customer_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.HasKey("CustomerId");

                    b.ToTable("customers", (string)null);

                    b.HasDiscriminator<string>("customer_type").HasValue("Customer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("BankAccountManagement.Models.CheckingAccount", b =>
                {
                    b.HasBaseType("BankAccountManagement.Models.Account");

                    b.Property<int>("NextCheckNumber")
                        .HasColumnType("int")
                        .HasColumnName("next_check_number");

                    b.HasDiscriminator().HasValue("checking");
                });

            modelBuilder.Entity("BankAccountManagement.Models.SavingsAccount", b =>
                {
                    b.HasBaseType("BankAccountManagement.Models.Account");

                    b.Property<double>("InterestRate")
                        .HasColumnType("double")
                        .HasColumnName("interest_rate");

                    b.HasDiscriminator().HasValue("savings");
                });

            modelBuilder.Entity("BankAccountManagement.Models.Company", b =>
                {
                    b.HasBaseType("BankAccountManagement.Models.Customer");

                    b.Property<string>("ABN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("abn");

                    b.Property<string>("ACN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("acn");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("industry");

                    b.HasDiscriminator().HasValue("company");
                });

            modelBuilder.Entity("BankAccountManagement.Models.Person", b =>
                {
                    b.HasBaseType("BankAccountManagement.Models.Customer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Occupation")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("occupation");

                    b.HasDiscriminator().HasValue("person");
                });

            modelBuilder.Entity("BankAccountManagement.Models.Account", b =>
                {
                    b.HasOne("BankAccountManagement.Models.Customer", "Customer")
                        .WithMany("Accounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BankAccountManagement.Models.Customer", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
